var s1 = 'hello';
var s2 = 'own';
var s3 = 'com';
var s4 = 'ua';
var n1 = 1;
var n2 = 10;
var n3 = -999;
var n4 = 123;
var n5 = 3.14;
var n6 = 2.7;
var n7 = 16;
var b1 = true;
var b2 = false;
console.log(s1);
console.log(s2);
console.log(s3);
console.log(s4);
console.log(n1);
console.log(n2);
console.log(n3);
console.log(n4);
console.log(n5);
console.log(n6);
console.log(n7);
console.log(b1);
console.log(b2);
var firstName = 'Panchuk';
var middleName = 'Sergii';
var lastName = 'Pavlovich';
console.log(firstName + ' ' + middleName + ' ' + lastName);
console.log("".concat(firstName, " ").concat(middleName, " ").concat(lastName));
var a = 100;
var b = '100';
var c = true;
console.log(typeof a, typeof b, typeof c);
var nameUser = prompt('your name');
var secondName = prompt('your last name');
var age = parseInt(prompt('your age'));
console.log("".concat(nameUser, " ").concat(secondName, " ").concat(age));
console.log(age);
